from __future__ import annotations

SCHEMA_VERSION = 19
SCHEMA_VERSION_LABEL = "database.schema.v19"
SNAPSHOT_MANIFEST_VERSION = "inaturalist.snapshot.v3"
NORMALIZED_SNAPSHOT_VERSION = "normalized.snapshot.v3"
ENRICHMENT_VERSION = "canonical.enrichment.v2"
QUALIFICATION_VERSION = "qualification.staged.v1"
EXPORT_VERSION = "export.bundle.v4"
REVIEW_OVERRIDE_VERSION = "review.override.v1"
PLAYABLE_CORPUS_VERSION = "playable_corpus.v1"
PACK_SPEC_VERSION = "pack.spec.v1"
PACK_DIAGNOSTIC_VERSION = "pack.diagnostic.v1"
COMPILED_PACK_VERSION = "pack.compiled.v1"
PACK_MATERIALIZATION_VERSION = "pack.materialization.v1"
COMPILED_PACK_V2_VERSION = "pack.compiled.v2"
PACK_MATERIALIZATION_V2_VERSION = "pack.materialization.v2"
PACK_POOL_VERSION = "pack_pool.v1"
SESSION_SNAPSHOT_VERSION = "session_snapshot.v1"
SESSION_SNAPSHOT_V2_VERSION = "session_snapshot.v2"
CONFUSION_EVENT_VERSION = "confusion.event.v1"
CONFUSION_AGGREGATE_VERSION = "confusion.aggregate.v1"
